name: deepmake
channels:
  - defaults
dependencies:
  - pip
  - python=3.10
  - pip:
      - anyio
      - click
      - fastapi
      - fastapi_utils
      - gradio
      - h11
      - huey
      - idna
      - pydantic
      - pymemcache
      - python-multipart
      - requests
      - sentry-sdk[fastapi]
      - sniffio
      - starlette
      - typing_inspect
      - uvicorn
      - psutil
      - pyjwt
      - pyside6
